apply plugin: 'com.palantir.external-publish-jar'

dependencies {
    api 'com.palantir.gradle.plugintesting:gradle-plugin-testing-junit'

    implementation 'com.palantir.gradle.utils:platform'
    implementation 'com.google.guava:guava'
    implementation 'commons-io:commons-io'
    implementation 'org.slf4j:slf4j-api'
}
