com.fasterxml.jackson.*:* = 2.22.1
com.fasterxml.jackson.core:jackson-annotations = 2.22
com.github.ben-manes.caffeine:caffeine = 3.2.4
org.immutables:* = 2.12.2
com.netflix.nebula:nebula-test = 12.1.0
org.junit.jupiter:* = 6.1.1
org.assertj:assertj-core = 3.27.7
org.junit.platform:* = 6.1.2
org.mockito:* = 5.23.0
com.palantir.gradle.utils:* = 0.27.0
com.google.guava:guava = 33.6.0-jre
one.util:streamex = 0.9.0
commons-io:commons-io = 2.22.0
org.slf4j:* = 2.0.17
org.apache.commons:commons-compress = 1.28.0
org.ow2.asm:asm = 9.10.1
com.palantir.gradle.failure-reports:* = 1.18.0
com.palantir.gradle.idea-configuration:gradle-idea-configuration = 0.8.0

# dependency-upgrader:OFF
com.palantir.baseline:* = 5.53.0
# dependency-upgrader:ON

# test dependencies
com.palantir.gradle.jdks:* = 0.79.0
com.palantir.gradle.jdkslatest:* = 0.31.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.47.0
org.checkerframework:checker-qual = 4.2.0
