import java.util.concurrent.Callable

apply plugin: 'java-gradle-plugin'
apply plugin: 'groovy'
apply plugin: 'java'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'com.palantir.external-publish-gradle-plugin'
apply plugin: 'org.unbroken-dome.test-sets'

testSets {
    integTest
}

tasks.build.dependsOn tasks.integTest

dependencies {
    api project(':gradle-jdks-distributions')
    api project(':gradle-jdks-json')
    api project(':gradle-jdks-setup')
    api project(':gradle-jdks-enablement')

    implementation('com.palantir.baseline:gradle-baseline-java') {
        exclude group: 'com.diffplug.spotless', module: 'spotless-plugin-gradle'
    }
    implementation 'com.palantir.gradle.failure-reports:gradle-failure-reports-exceptions'
    implementation 'com.palantir.gradle.utils:lazily-configured-mapping'
    implementation 'com.google.guava:guava'
    implementation 'commons-io:commons-io'
    implementation 'org.apache.commons:commons-compress'
    implementation 'org.ow2.asm:asm'
    implementation 'com.palantir.gradle.idea-configuration:gradle-idea-configuration'
    implementation 'com.palantir.gradle.utils:platform'

    compileOnly 'com.palantir.gradle.auto-parallelizable:auto-parallelizable-annotations'
    compileOnly 'org.immutables:value::annotations'
    annotationProcessor 'com.palantir.gradle.auto-parallelizable:auto-parallelizable'
    annotationProcessor 'org.immutables:value'

    testImplementation gradleTestKit()
    testImplementation project(':gradle-jdks-settings')
    testImplementation project(':gradle-jdks-test-common')
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'com.palantir.gradle.plugintesting:gradle-plugin-testing-junit'
    //testRuntimeOnly files(createClasspathManifest)

    gradlePluginForTesting project(':gradle-jdks-settings')
    gradlePluginForTesting 'com.palantir.gradle.jdkslatest:gradle-jdks-latest'
    gradlePluginForTesting 'com.palantir.baseline:gradle-baseline-java'
    gradlePluginForTesting 'com.palantir.gradle.jdks:gradle-jdks-settings'
//    gradlePluginForTesting 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin'
//    gradlePluginForTesting 'com.palantir.gradle.shadow-jar:gradle-shadow-jar'
//    gradlePluginForTesting 'com.gradle.publish:plugin-publish-plugin'
//    gradlePluginForTesting 'com.palantir.gradle.consistentversions:gradle-consistent-versions'
}

gradlePlugin {
    plugins {
        jdks {
            id = 'com.palantir.jdks'
            displayName = 'Palantir JDK Auto-provisioning Plugin'
            description = 'Auto-provisions specific versions of JDKs'
            implementationClass = 'com.palantir.gradle.jdks.JdksPlugin'
            tags.addAll("java", "jdks")
        }
        palantirCa {
            id = 'com.palantir.jdks.palantir-ca'
            displayName = 'Palantir CA for gradle-jdks'
            description = 'Includes the Palantir CA from the system truststore'
            implementationClass = 'com.palantir.gradle.jdks.PalantirCaPlugin'
            tags.addAll("java", "jdks", "palantir ca")
        }
    }
    website = 'https://github.com/palantir/gradle-jdks'
    vcsUrl = 'https://github.com/palantir/gradle-jdks'
    description = 'Download specific JDKs versions automatically'
}

tasks.withType(JavaCompile).configureEach {
    it.options.errorprone.disable 'JavaxInjectOnAbstractMethod'
    it.options.errorprone.disable 'StrictUnusedVariable'
    it.options.errorprone.disable 'GradleTestPluginsBlock'
}


tasks.withType(Test) {
    environment(Map.of("PROJECT_VERSION", project.version))
    systemProperty 'ignoreDeprecations', 'true'
    dependsOn project(':gradle-jdks-settings').tasks.withType(PluginUnderTestMetadata.class)
}

tasks.withType(ProcessResources.class).configureEach {
    from(project(':gradle-jdks-setup').tasks.named('fatJar')) {
        rename { 'gradle-jdks-setup.jar' }
    }
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
    configurationCacheEnabled = true
}


//def pluginClasspathRuntimeOnly = configurations.create('pluginClasspathRuntimeOnly')
//dependencies {
//    add(pluginClasspathRuntimeOnly.name, project(':gradle-jdks-settings'))
//}
//tasks.named('pluginUnderTestMetadata', PluginUnderTestMetadata) {
//    pluginClasspath.from(pluginClasspathRuntimeOnly)
//}

evaluationDependsOn(':gradle-jdks-settings')
evaluationDependsOn(':gradle-jdks-setup-common')
evaluationDependsOn(':gradle-jdks-enablement')
//
//println getExtensions().getByType(GradlePluginDevelopmentExtension.class).pluginSourceSet.getOutput().getFiles()
//
tasks.withType(PluginUnderTestMetadata).configureEach {
    def provider = project.provider(classpathForPlugin(project(':gradle-jdks-settings'), project(':gradle-jdks')))
    pluginClasspath.setFrom(provider)
}
//
//
private static Callable<FileCollection> classpathForPlugin(Project settingsProject, Project jdksProject) {
    return () -> {
        GradlePluginDevelopmentExtension extension = settingsProject.getExtensions().getByType(GradlePluginDevelopmentExtension.class);
        SourceSet settingsSourceSet = extension.getPluginSourceSet();
        Configuration settingsRuntimeClasspath = settingsProject.getConfigurations().getByName(settingsSourceSet.getRuntimeClasspathConfigurationName());
        ArtifactView settingsView = settingsRuntimeClasspath.getIncoming().artifactView(config ->
                config.componentFilter(JavaGradlePluginPlugin::excludeGradleApi)
        );

        GradlePluginDevelopmentExtension extension2 = jdksProject.getExtensions().getByType(GradlePluginDevelopmentExtension.class);
        SourceSet jdksSourceSet = extension2.getPluginSourceSet();
        Configuration jdksRuntimeClasspath = jdksProject.getConfigurations().getByName(jdksSourceSet.getRuntimeClasspathConfigurationName());
        ArtifactView jdksView = jdksRuntimeClasspath.getIncoming().artifactView(config ->
                config.componentFilter(JavaGradlePluginPlugin::excludeGradleApi)
        );

        // Get files from view first
        def settingsViewFiles = settingsView.getFiles()
        def viewFilePaths = settingsViewFiles.collect { it.absolutePath }.toSet()
        
        // Filter view2 to only include files not in view
        def jdksViewFilesWithNoDuplicates = jdksView.getFiles().findAll { file ->
            file.absolutePath.startsWith("/Volumes/git/gradle-jdks/") || file.absolutePath.contains("palantir")  || file.absolutePath.contains("palantir") || file.absolutePath.contains("guava") || file.absolutePath.contains("apache")
            //!viewFilePaths.contains(file.absolutePath)
        }
        
        return settingsProject.getObjects().fileCollection().from(
                settingsSourceSet.getOutput(),
                jdksSourceSet.getOutput(),
                settingsViewFiles,
                jdksViewFilesWithNoDuplicates,
        );
    };
}

//
//tasks.withType(PluginUnderTestMetadata).configureEach {
//    pluginClasspath.setFrom(
//            rootProject.project(':gradle-jdks-settings').sourceSets.main.output,
//            rootProject.project(':gradle-jdks').sourceSets.main.output,
//    )
//}