FROM @BASE_IMAGE@
COPY ./gradle /gradle
RUN apt-get update && apt-get install -y curl && echo "alias curl='curl -k'" >> /root/.bash_profile && chmod +x /gradle/testing-script.sh
CMD ["/bin/bash", "-i", "-c", "/gradle/testing-script.sh"]
