apply plugin: 'java'
apply plugin: 'com.palantir.external-publish-jar'

dependencies {
    // Avoid adding large compile dependencies here, as they will also be added in the gradle-jdks-setup-all*.jar using the fatJar task
    implementation 'com.fasterxml.jackson.core:jackson-annotations'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// Used by gradle-jdks-setup so it needs to keep Java 11 compatibility.
javaVersion {
    target = 11
}
